### PR TITLE
Don't alter `require.paths`.

### PR DESCRIPTION
**Pull request by TooTallNate**
Feature was removed in node 0.5.x.

This should get things working in the up and coming versions.

### CODE REVIEW

**Comment by TooTallNate** [comment]
node v0.6.0 is released now. Can this be merged please and an npm version bump? It would be appreciated!

**Comment by lbjay** [comment]
+1

**Comment by edsu** [comment]
+1

**Comment by astro** [comment]
+3

**Comment by TooTallNate** [comment]
@gf3 Might need to @mention you before you get these notifications...

**Comment by yodiaditya** [comment]
+4

**Comment by gf3** [comment]
Sorry guys, I've been crazy busy lately, I'll get on these.

**Comment by gf3** [comment]
`0.2.27` published

**Pull request merged**
