### PR TITLE
Fails to install with NPM 1.0.1rc9

### PR DESCRIPTION
**Pull request by stephank**
I was getting strange errors when installing with NPM 1.0.1rc9:

```
$ npm install
npm ERR! error installing irc-js@0.2.17 Error: ENOENT, No such file or directory '[...]/node_modules/irc-js/node_modules/PanPG/package.json'
[...]
npm not ok
```

I'm not sure if NPM 1.0 tries to be smart and deal with a 0.3 directory structure or something, but clearing out `node_modules/.npm` and `node_modules/coloured-log*` fixes the problem. Afterwards, `npm install` simply reinstalls coloured-log in a 1.0-fashion.

```
$ npm ls
irc-js@0.2.17 /home/shteef/Source/orona/node_modules/irc-js
└─┬ coloured-log@0.9.4
  ├── coloured@0.2.0
  └── log@1.1.1
```

Regardless of the PanPG reference in the error, this doesn't seem to be the real problem. In fact, with the above, NPM doesn't mind the PanPG directory and merely goes about.

Hope this is okay with NPM 0.3.

### CODE REVIEW

**Comment by gf3** [comment]
Thanks for filing the issue! I bet the deps just need to be rebundled with npm 1.0. I'll report back!

**Comment by cyle** [comment]
so wait, what did you do to resolve this, stephank? I'm trying to install irc-js with npm ("npm install irc-js") and it still throws this same "Error: ENOENT, No such file or directory" error. I'm using npm 1.0.6. thanks!

**Comment by gf3** [comment]
Sorry, I was waiting until the release of npm 1.0 to fix this bug. Fix coming soon.

**Comment by stephank** [comment]
I still can't install. I'm not sure why it's complaining either, to be honest.

I created an empty directory, and tried a local install within it:

```
npm ERR! error installing irc-js@0.2.18 Error: ENOENT, No such file or directory '/home/shteef/foo/node_modules/irc-js/node_modules/PanPG/package.json'
```

Or when I clone irc-js, and run `npm install` inside the irc-js dir:

```
npm ERR! Error: ENOENT, No such file or directory '/home/shteef/foo/IRC-js/node_modules/PanPG/package.json'
```

I think the latter was my workaround for when I originally reported the bug. But it doesn't seem to budge at all, now.

**Comment by stephank** [comment]
Opened up an NPM issue, because I'd like the learn the correct way to fix this:
https://github.com/isaacs/npm/issues/890

**Comment by gf3** [comment]
Yes, I've actually looked into this, it is infact an npm issue. It should not be failing (or even touching) things w/o a `package.json`. You can stick whatever crap you like in `node_modules`, they don't have to be npm packages.

**Comment by TooTallNate** [comment]
My commit here makes this module "npm 1.0"-happy:
https://github.com/TooTallNate/IRC-js/commit/3601d5bdd1d5dadc21324eef5bcf2ce00efaf490

**Comment by gf3** [comment]
Cool, thank you. I've just been quietly waiting for isaacs to fix npm, heh.

**Comment by TooTallNate** [comment]
Indeed, the npm bug is annoying. This is a simple workaround for it though (adding the necessary package.json), so you'd might as well merge IMO and republish to npm, so we can use it now.

**Comment by gf3** [comment]
Done!

**Comment by TooTallNate** [comment]
Apologies. My above commit is partially broken. See this commit for the fix:
https://github.com/TooTallNate/IRC-js/commit/897f148cc79e34e1c0773242aab40d3264feebb5

You can easily apply from within the repo like so:

```
curl https://github.com/TooTallNate/IRC-js/commit/897f148cc79e34e1c0773242aab40d3264feebb5.patch | git am
```

Cheers!

**Comment by gf3** [comment]
I've got you as a remote so I can simply cherry-pick it. Thanks.

**Pull request closed without merging**
