### PR TITLE
Remove 'coloured-log'

### LINKED ISSUE #27: 'coloured-log' shouldn't be a bundled dependency...
PanPG is ok since it's not already published on npm, but coloured-log needs to go. It can be installed from npm fine, and on top of that, the irc-js version that's currently up on npm has an incomplete checkout of 'coloured-log', it's dependencies aren't checked out. This leads to npm saying that irc-js is missing dependencies immediately after installation.

Just remove [this line](https://github.com/gf3/IRC-js/blob/a983e8f5bc49cbe4dc98281f886cbaa34b6f1c90/package.json#L21) and `rm -rf node_modules/coloured-log` and republish on npm and we should be good! Thanks in advance!

### PR DESCRIPTION
**Pull request by TooTallNate**
This closes #27. Remove the `coloured-log` module completely, as it's rather out of the scope of this module.

Alone this pull request helps, although it's still rather rude to call the `console` functions inside of a re-usable module. Might I recommend that the `console.info`/`console.error` calls in `lib/irc.js` be changed to: `this.emit('info', 'message')` so the dev's have the option to do what they want with the events. I can set up a pull request for this as well if you'd like. Let me know...

### CODE REVIEW

**Comment by broofa** [comment]
Events to get log info? Isn't this sort of thing usually done with a debug property?  e.g. "ircjs.debugLevel=ircjs.(DEBUG/INFO/WARN/ERROR)" to set the min level of errors to the module should log.

**Comment by TooTallNate** [comment]
As someone using the module, I'd rather not be forced into `IRC-js` forcing me to log via it's mechanism (whether it be coloured-log or plain ol `console.log` or whatever). The point is I _do_ want the debugging information, but I'd rather integrate the module with the logging system our app already has in place, and not have mixed up kinds of logging. This is best done by emitting events, i.e. `info` and `error`.

In this case, it's particularly nice to do this because in node, if an `error` event gets emitted on an EventEmitter, and there's no listeners attached for that event, then it will throw globally and stop node. So the `options.dye` option could be removed since it would be essentially the same thing. I can prepare a pull request but I'd rather wait for @gf3 to merge this first.

**Comment by broofa** [comment]
Maybe compromise on using emit(), but provide a built-in logging listener for the 90% case, so people don't have to write the same code over and over?  Enabling logging would look something like:

```
ircjs.on('info', ircjs.consoleLogger);
```

**Comment by TooTallNate** [comment]
ya sure, like that. I think break apart the two like this:

``` javascript
ircjs.consoleInfoLogger = console.info;
ircjs.consoleErrorLogger = console.error;
```

which could be controlled by the already existing `options.log`. That would be a very nice interface in my opinion; backwards compatible and extensible.

**Comment by gf3** [comment]
Sorry gents, I just got back from vacation. I'll get this merged ASAP.

**Comment by gf3** [comment]
Thanks @TooTallNate!

**Comment by TooTallNate** [comment]
@gf3, what are your thoughts with changing the `console.error/info` calls to `emit` calls?

**Comment by gf3** [comment]
@TooTallNate I think that's a really great idea! Much cleaner than logging by default.

**Comment by gf3** [comment]
@TooTallNate Maybe `log:info` and `log:error` or some such. I don't think we need to emit an `error` event because there will likely be an actual Error accompanying that log message.

**Pull request merged**
